#Folder where Cityscapes Data is downloaded
CITYSCAPES_ROOT_DIR = "/media/roovedot/PHILIPS/cityscapesRootFolder/"

# Directory where the project is located (for relative paths)
PROYECT_ROOT_DIR = "/mnt/01DB23CE72C96D00/Pr.Inv.JavierFernandez/Lane_Detection/Code/UNet"

# Directory where the data generated by the code will be stored (I used the CITYSCAPES_ROOT_DIR, but in case you want to store it elsewhere)
DATA_ROOT_DIR = CITYSCAPES_ROOT_DIR